### Site info:
title: "Nguyen Tay"
tagline: "Viual Art"
author: Sun Seng David TAN (a.k.a Sunix)
email: sunix@sunix.org
description: "Nguyen Tay website: visual art"
keywords: "Visual Art"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nguyentay.art" # the base hostname & protocol for your site
locale: en_EN

### Personal info and site tools info:
favicon:     "/images/favicon.ico"


### Site setting:
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    fr:
      Aboutme: "A propos de moi"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Derniers Posts"
      Tags: "Tags"
      Previous: "Précédent"
      Next: "Suivant"
      PostedInCategories: "Posté dans"
      Taggedwith: "taggé"
      PostDate: "le "
      Google_search: "Recherche"
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "
      Google_search: "站内搜索"
### your Blogroll info, only name can shown on the page.

Blogroll:
      - name: Freshman
        href: http://yulijia.net/freshman
        title: Another Jekyll blog theme
      - name: author's website
        href: http://yulijia.net/
        title: Lijia Yu's website


### Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
excerpt_separator: <!-- more -->

plugins: [jekyll-paginate]
